name: Doctor

on:
  workflow_dispatch:

jobs:
  doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best effort)
        run: |
          python -V
          pip install -r requirements.txt || true
          pip install feedparser || true

      - name: Print runner signature
        run: |
          sed -n '1,80p' runner.py || true
          grep -n "choices=" runner.py || true

      - name: Quick papers dry-run (non-fatal)
        run: |
          mkdir -p logs
          python runner.py --task papers --query "agentic RAG memory tool use 2024 arXiv" --max_results 2 || true

      - name: Show summary (if exists)
        run: |
          test -f logs/run_summary.json && cat logs/run_summary.json || echo "no summary file yet"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs
          if-no-files-found: ignore