name: agentic-rag
on:
  schedule:
    - cron: "0 12 * * 1"   # segundas 12:00 UTC (opcional)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml feedparser

      - name: Debug – listar arquivos e localizar policy
        run: |
          pwd
          git rev-parse --short HEAD
          ls -la
          echo "--- procurando policy ---"
          find . -maxdepth 3 -type f -iname "policy.y*ml" -print || true
          echo "--- fim debug ---"

      - name: Ensure dirs
        run: |
          mkdir -p logs
          mkdir -p outputs

      - name: Run agentic rag
        run: python runner.py --task agentic_rag --max_results 5

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: Upload summary and csv
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/