name: quick-agentic

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guard contra trechos inválidos no app.py
        run: |
          set -e
          test -f app.py
          if grep -nE '^\s*\*\*\*' app.py; then
            echo "❌ Encontrado marcador '***' no app.py (cola incompleta)."
            exit 1
          fi
          if grep -nE '^\s*-\s*name:\s' app.py; then
            echo "❌ Parece que colou trecho de YAML do Actions dentro do app.py."
            exit 1
          fi
          echo "✓ Guard passou"
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml beautifulsoup4 requests tenacity
      - name: Run default stub_v3
        run: |
          python runner.py --task stub_v3 --profile whatsapp_acolhedor --query "teste rápido"
      - uses: actions/upload-artifact@v4
        with:
          name: quick-agentic
          path: outputs/**
          if-no-files-found: warn
