name: agent-tests-v2

on:
  workflow_dispatch:
    inputs:
      query:
        description: "Consulta rápida para o teste de papers"
        required: false
        default: "autonomous agents memory tool use"

permissions:
  contents: read

concurrency:
  group: agent-tests-v2-${{ github.ref }}
  cancel-in-progress: false

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          mkdir -p logs outputs state
          pip freeze > logs/pip_freeze.txt

      - name: Sanity checks (arquivos e imports)
        run: |
          set -e
          echo ":: Python $(python -V)" | tee -a logs/diag.txt
          echo ":: Lista de arquivos" | tee -a logs/diag.txt
          ls -R | tee -a logs/diag.txt
          python - <<'PY'
          import importlib, json, pathlib, sys
          results = {}
          for mod in ["runner","stubs.active_rag_stub_v3","tasks.papers_arxiv"]:
              try:
                  importlib.import_module(mod)
                  results[mod] = "OK"
              except Exception as e:
                  results[mod] = f"ERROR: {e}"
          pathlib.Path("logs/imports.json").write_text(json.dumps(results, indent=2), encoding="utf-8")
          print(results)
          PY

      - name: Teste rápido — stub_v3
        run: |
          set -e
          python runner.py --task stub_v3 --profile whatsapp_acolhedor --query "Qual é a política de fretes e prazo?"

      - name: Teste rápido — papers (tolerante a erro de rede)
        continue-on-error: true
        run: |
          set -e
          q="${{ inputs.query }}"
          python runner.py --task papers --query "$q"

      - name: Upload diagnostics
        uses: actions/upload-artifact@v4
        with:
          name: agent-diagnostics
          path: |
            outputs/**
            logs/**
            state/**
            *.json
          if-no-files-found: warn