name: agentic-rag
on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar deps
        run: pip install feedparser
      - name: Executar runner (papers no arXiv)
        run: python runner.py --task papers --query "agentic rag memory tools" --max_results 3
      - name: Anexar logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/