name: arXiv (standalone)

on:
  workflow_dispatch:
    inputs:
      query:
        description: 'Consulta arXiv'
        default: '(agentic OR "AI agents") AND (RAG OR "retrieval-augmented") AND (memory OR "tool chain" OR workflow)'
        required: true
      max_results:
        description: 'Quantidade de artigos'
        default: '5'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar runner (arxiv)
        env:
          QUERY: ${{ github.event.inputs.query }}
          MAX_RESULTS: ${{ github.event.inputs.max_results }}
        run: |
          python runner.py --task arxiv --query "$QUERY" --max_results "$MAX_RESULTS"

      - name: Anexar resultados
        uses: actions/upload-artifact@v4
        with:
          name: arxiv_results
          path: arxiv_results.json
          if-no-files-found: warn