name: arXiv (standalone)

on:
  workflow_dispatch:
    inputs:
      query:
        description: "Consulta arXiv"
        required: false
        default: '("agentic RAG" OR "tool use") AND memory'
      max_results:
        description: "Qtd de artigos"
        required: false
        default: '10'
      time_range:
        description: "Intervalo (ex: 2023-2025)"
        required: false
        default: '2023-2025'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser arxiv
      - name: Executar runner (papers)
        run: |
          python runner.py \
            --task papers \
            --query "${{ inputs.query }}" \
            --max_results "${{ inputs.max_results }}" \
            --time_range "${{ inputs.time_range }}"
      - name: Anexar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: arxiv_papers
          path: |
            run_summary.json
            logs.txt