.github/workflows/staging.yml
      - name: Guard contra trechos inválidos no app.py
        run: |
          set -e
          test -f app.py
          if grep -nE '^\s*\*\*\*' app.py; then
            echo "❌ Encontrado marcador '***' no app.py (cola incompleta)."
            exit 1
          fi
          if grep -nE '^\s*-\s*name:\s' app.py; then
            echo "❌ Parece que colou trecho de YAML do Actions dentro do app.py."
            exit 1
          fi
          echo "✓ Guard passou"