name: agentic-rag

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # roda todo dia 03:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          pwd
          ls -la
          echo "Looking for app.py..."
          test -f app.py && echo "✓ app.py found" || (echo "✗ app.py NOT found at repo root" && exit 1)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jq  # utilitário para pretty-print (puro Python)

      - name: Check minimal imports (fast fail)
        run: |
          python - << 'PY'
          import fastapi, uvicorn, fpdf
          print("✓ FastAPI/uvicorn/fpdf import OK")
          PY

      - name: Inject secrets (OpenAI)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "❌ OPENAI_API_KEY não configurada (Settings → Secrets and variables → Actions)."
            exit 1
          fi
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> $GITHUB_ENV
          echo "LLM_MODEL=gpt-4.1"