name: agentic-rag

on:
  workflow_dispatch:
    inputs:
      task:
        description: "O que rodar"
        required: true
        default: "stub_v3"
        type: choice
        options: [stub_v3, papers, demo]
      profile:
        description: "Perfil/Preferências"
        required: true
        default: "default"
        type: choice
        options: [default, whatsapp_acolhedor, email_formal]
      query:
        description: "Pergunta/consulta (usada em papers e demo)"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: agentic-rag-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # deps usadas pelo runner
          pip install feedparser pyyaml beautifulsoup4 requests tenacity arxiv

      - name: Run runner.py
        env:
          TASK:    ${{ inputs.task }}
          PROFILE: ${{ inputs.profile }}
          QUERY:   ${{ inputs.query }}
        run: |
          set -e
          echo "TASK=$TASK PROFILE=$PROFILE QUERY=$QUERY"
          python runner.py --task "$TASK" --profile "$PROFILE" --query "$QUERY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agent-test-results
          path: |
            outputs/**
            logs/**
            state/**
            *.json
          if-no-files-found: warn