name: agentic-rag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # permite rodar manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set env
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "❌ OPENAI_API_KEY não configurada em Secrets → Actions."
            exit 1
          fi
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> $GITHUB_ENV
          echo "LLM_MODEL=gpt-4.1" >> $GITHUB_ENV

      - name: Start API (background)
        run: |
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 --reload > uvicorn.log 2>&1 &
          echo $! > uv.pid
          sleep 2

          - name: Wait health
        run: |
          for i in $(seq 1 40); do
            curl -fsS http://localhost:8000/health && exit 0 || sleep 0.5
          done
          echo "❌ Healthcheck falhou"
          echo "---- uvicorn.log ----"
          cat uvicorn.log || true
          exit 1

      - name: Run /run (JSON)
        run: |
          curl -fsS -X POST http://localhost:8000/run \
            -H "Content-Type: application/json" \
            -d '{"query":"Crie um plano de MVP em 1 página para o projeto Biblioteca Viva.","formato":"texto"}' \
            -o out_run.json
          jq . out_run.json | head -n 50 || true

      - name: Run /run_pdf (gera colabIA_resultado.pdf)
        run: |
          curl -fsS -X POST http://localhost:8000/run_pdf \
            -H "Content-Type: application/json" \
            -d '{"query":"Crie um plano de MVP em 1 página para o projeto Biblioteca Viva.","formato":"texto"}' \
            --output colabIA_resultado.pdf

      - name: Run plano Ana (JSON)
        run: |
          curl -fsS -X POST http://localhost:8000/run \
            -H "Content-Type: application/json" \
            -d '{"query":"Plano para atender a Ana hoje com upsell e próxima ação","formato":"texto"}' \
            -o out_ana.json
          jq . out_ana.json | head -n 50 || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: colabIA-results
            path: |
              out_run.json
              out_ana.json
              colabIA_resultado.pdf
              uvicorn.log

      - name: Stop API
        if: always()
        run: |
          if [ -f uv.pid ]; then kill $(cat uv.pid) || true; fi
          sleep 1
          pkill -f "uvicorn app:app" || true