name: quick-papers-personal
on: { workflow_dispatch: {} }

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt
          pip install feedparser pyyaml beautifulsoup4 requests tenacity
      - name: Run papers (personalization & memory)
        env:
          QUERY: >
            "AI agents" AND RAG AND (memory OR "user profile" OR personalization
            OR "episodic memory" OR "semantic memory")
        run: |
          python runner.py --task papers --profile default --query "$QUERY"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agent-test-results
          path: |
            outputs/**
            logs/**
            state/**
            *.json
          if-no-files-found: warn